# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'GetFun' do
#AFNetworking需要2.5版本，否则无法请求微信的https接口(本地关闭了ATS)
pod 'AFNetworking', '2.5.4'
pod 'BlocksKit', '~> 2.2.5'
pod 'pop', '~> 1.0.8'

#Mantle 2.x不支持iOS 7
pod 'Mantle', '1.5.6'

pod 'DateTools', '~> 1.7.0'
pod 'RSKImageCropper', '~> 1.5.0'

pod 'WebViewJavascriptBridge', '4.1.4'
pod 'Qiniu', '~> 7.0'

#pod 'JZNavigationExtension', '~> 1.3.4'
pod 'FastttCamera', '~> 0.3.4'
pod 'ActionSheetPicker-3.0', '~> 2.0.3'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SWTableViewCell', '~> 0.3.7'

#pod 'YYKit', '~> 0.9.11'
pod 'HPGrowingTextView', '~> 1.1'
pod 'DTRichTextEditor', '~> 1.6.11'
pod 'TTTAttributedLabel', '~> 1.13.4'
pod 'NYXImagesKit', '~> 2.3'

pod 'AMapLocation', '~> 1.1.1'
pod 'AMapSearch', '~> 3.2.0'
pod 'AMap2DMap', '~> 3.2.0'



pod 'Fabric', '~> 1.6.4'
pod 'Crashlytics', '~> 3.6.0'
pod 'UMengAnalytics-NO-IDFA', '~> 3.6.7'
pod 'CocoaLumberjack', '~> 2.2.0'

end

